### PR TITLE
XML support

### PR DESCRIPTION
**Pull request by olivergeorge**
I've done a little work to make hickory support basic XML parsing and rendering.  I'm wondering if this is something you think could be added to the main hickory repo.

My goal was parse an XML document, make changes to it and then serialise the back to XML.  Where possible I wanted the rendered XML to be as close to the original as practical to simplify debugging.

The changes needed were all quite minor really:
- Use "application/xml" when calling js/DOMParser
- Respect case of tag names
- Render with <?xml .. ?> preamble
- Render a closed tag if no children are present

I cut and pasted a lot to keep things simple (for me) but I think you will have ideas on a more integrated approach.

I'm concious that this code relies on js/DOMParser which might be more restrictive than hickory is otherwise.  In particular it's an IE9+ approach.

### CODE REVIEW

**Comment by lvh** [comment]
I also would like XML support. I'm currently doing it like this:

```clojure
(defn parse-xml
  "Parse an XML string into DOM objects."
  [s]
  (.parseFromString (js/DOMParser.) s "text/xml"))
```

I'm using as-hiccup now and it seems to work fine. I definitely understand why you'd want to use goog.dom.xml though.

Perhaps this just needs a few tests and it's good to go?

**Comment by lvh** [comment]
So, the thing that I have there doesn't really work because my code doesn't fix `as-hiccup` making all tags lowercase, which this PR handles.

**Comment by lvh** [comment]
I just backported this, and it worked like a charm. I also added:

```clojure
(def as-hiccup-xml
  (comp hickory-to-hiccup as-hickory-xml))
```

What would it take to get this merged? Should I add unit tests or something?

**Comment by lvh** [comment]
I wonder if it might make sense to use the browser DOM APIs to reproduce a document and then serialize it.

**Comment by port19x** [comment]
I believe [data.xml](https://github.com/clojure/data.xml) is the proper tool to parse XML and will soon-ish document it in a prominent place in hopes that people seeking an XML parser will find an XML parser and not "misuse" an HTML parser for that usecase.

> IE9+ sounds good enough and the code is pretty similar to the existing so it all sounds good.
> 
> I agree there probably will be people expecting this feature to work outside browser, including on node platform. Also I am wondering if it would not make more sense to add ClojureScript support to [data.xml](https://github.com/clojure/data.xml) rather than XML support to `hickory`.

The main considerations here are scope creep and expertise.

Expertise: I write web-scraping programs and am familiar with the ins and outs of network requests and HTML, not XML.
Scope Creep: Explicit XML support would near double the scope of the project and take resources away from enhancing hickory's quality as an HTML parser.

I'll try my best to make hickory extensible and applicable to other hiccup producing libraries (#24)
I won't support XML (#29) (#63)

**Pull request closed without merging**
